# Generated by Django 5.1.2 on 2025-01-29 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_alter_post_options_alter_like_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="posts.comment",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="posts.post",
            ),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("comment__isnull", True), ("post__isnull", False)),
                    models.Q(("comment__isnull", False), ("post__isnull", True)),
                    _connector="OR",
                ),
                name="like_must_have_either_post_or_comment",
            ),
        ),
    ]
