services:
  web:
    image: rachealcodez/vibez:latest
    env_file:
      - .env
    environment:
      - DB_NAME=${DATABASE_NAME}
      - DB_USER=${DATABASE_USER}
      - DB_PASSWORD=${DATABASE_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
      - CLOUD_NAME=${CLOUD_NAME}
    ports:
      - "8003:8000"
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "nc", "-z", "db", "5432" ]
      interval: 5s
      timeout: 5s
      retries: 5
    command: >
      sh -c "python manage.py migrate &&
             gunicorn vibes.wsgi:application --bind 0.0.0.0:8000"

  db:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  default:
    name: vibes_network
volumes:
  postgres_data: