services:
  web:
    image: rachealcodez/vibez:latest
    env_file:
      - .env
    environment:
      - DB_NAME=${DATABASE_NAME}
      - DB_USER=${DATABASE_USER}
      - DB_PASSWORD=${DATABASE_PASSWORD}
      - DB_HOST=localhost
      - DB_PORT=5432
    ports:
      - "8001:8000"
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "nc", "-z", "db", "5432" ]
      interval: 5s
      timeout: 5s
      retries: 5
    command: >
      sh -c "python manage.py migrate &&
             gunicorn vibes.wsgi:application --bind 0.0.0.0:8000"

  db:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  postgres_data:
