name: Deploy to EC2 with Docker Image

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t vibez:latest -f vibes/Dockerfile vibes

      # Step 3: Push Docker Image to Registry
      # Replace with your Docker registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker tag vibez:latest rachealcodez/vibez:latest
          docker push rachealcodez/vibez:latest

      # Step 4: Deploy Docker Image on EC2
      - name: Transfer Docker Compose or Deployment Script
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.IP_ADDRESS }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: /docker-compose.yaml
          target: /home/ubuntu/api

      - name: Deploy Docker Container on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.IP_ADDRESS }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            mkdir -p /home/ubuntu/api
            cd /home/ubuntu/api/vibes
            
            docker-compose down || true
            docker-compose pull
            docker-compose up -d
